import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(dashboard)/components/Navber/Navber";
import Sidebar from "./(dashboard)/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full lg:w-[1440px] mx-auto bg-[#F6F6F6]">
      <Navbar />
      <div className="flex mt-8 mx-[50px] gap-12">
        <Sidebar />
        {children}
      </div>
    </div>
  );
}
